=== HKristof2130/JPTJY2_XMLGyak/Féléves_feladat/XMLSchemaJPTJY2.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="nba" type="nbaType">
  </xs:element>

  <xs:complexType name="idotartamType">
    <xs:sequence>
      <xs:element type="xs:date" name="kezdet"/>
      <xs:element type="xs:date" name="veg"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="szezonType">
    <xs:sequence>
      <xs:element type="xs:int" name="nevezettcsapatok_szama"/>
      <xs:element type="xs:string" name="teljes_szezon"/>
      <xs:element type="idotartamType" name="idotartam"/>
    </xs:sequence>
    <xs:attribute ref="sz_id" use="required"/>
  </xs:complexType>

  <xs:complexType name="csapatType">
    <xs:sequence>
      <xs:element type="xs:string" name="nev"/>
      <xs:element type="xs:string" name="arena"/>
      <xs:element type="xs:int" name="bajnoki_cimek"/>
    </xs:sequence>
    <xs:attribute ref="cs_id" use="required"/>
  </xs:complexType>

  <xs:complexType name="edzoType">
    <xs:sequence>
      <xs:element type="xs:string" name="nev"/>
      <xs:element type="xs:string" name="csapat"/>
      <xs:element type="xs:int" name="aktiv_szezon"/>
    </xs:sequence>
    <xs:attribute ref="e_id" use="required"/>
    <xs:attribute ref="cs_e" use="required"/>
  </xs:complexType>

  <xs:complexType name="stabtagType">
    <xs:sequence>
      <xs:element type="xs:string" name="nev"/>
      <xs:element type="xs:string" name="csapat"/>
      <xs:element type="xs:string" name="beosztas"/>
    </xs:sequence>
    <xs:attribute ref="s_id" use="required"/>
    <xs:attribute ref="cs_s" use="required"/>
  </xs:complexType>

  <xs:complexType name="jatekosType">
    <xs:sequence>
      <xs:element type="xs:string" name="nev"/>
      <xs:element type="xs:string" name="csapat"/>
      <xs:element type="xs:byte" name="kor"/>
      <xs:element type="xs:string" name="poizicio" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
    <xs:attribute ref="j_id" use="required"/>
    <xs:attribute ref="cs_j" use="required"/>
  </xs:complexType>

  <xs:complexType name="nevezett_csapatType">
    <xs:sequence>
      <xs:element type="xs:byte" name="szezon_szama"/>
      <xs:element type="xs:string" name="csapat_neve"/>
    </xs:sequence>
    <xs:attribute ref="sz_a_id" use="required"/>
    <xs:attribute ref="sz_n_id" use="required"/>
  </xs:complexType>

  <xs:complexType name="nbaType">
    <xs:choice maxOccurs="unbounded" minOccurs="1">
      <xs:element type="szezonType" name="szezon" maxOccurs="unbounded" minOccurs="3">
      </xs:element>

      <xs:element type="csapatType" name="csapat" maxOccurs="unbounded" minOccurs="3">
      </xs:element>

      <xs:element type="edzoType" name="edzo" maxOccurs="unbounded" minOccurs="3">
      </xs:element>

      <xs:element type="stabtagType" name="stabtag" maxOccurs="unbounded" minOccurs="3">
      </xs:element>

      <xs:element type="jatekosType" name="jatekos" maxOccurs="unbounded" minOccurs="3">
      </xs:element>

      <xs:element type="nevezett_csapatType" name="nevezett_csapat" maxOccurs="unbounded" minOccurs="3">
      </xs:element>

    </xs:choice>
  </xs:complexType>

  <!-- 
    Attribútomok definiálása
   -->
  <xs:attribute type="xs:int" name="sz_id" />

  <xs:attribute type="xs:int" name="cs_id" />

  <xs:attribute type="xs:int" name="e_id" />
  <xs:attribute type="xs:int" name="cs_e" />

   <xs:attribute type="xs:int" name="s_id" />
   <xs:attribute type="xs:int" name="cs_s" />

   <xs:attribute type="xs:int" name="j_id" />
   <xs:attribute type="xs:int" name="cs_j" />

   <xs:attribute type="xs:int" name="sz_a_id" />
   <xs:attribute type="xs:int" name="sz_n_id" />

   <xs:element name="keys">

    <!-- 
        Elsodleges kulcsok
       -->
    <xs:key name="Szezon_id">
      <xs:selector xpath="szezon"></xs:selector>
      <xs:field xpath="@sz_id"></xs:field>
    </xs:key>

    <xs:key name="Csapat_id">
      <xs:selector xpath="csapat"></xs:selector>
      <xs:field xpath="@cs_id"></xs:field>
    </xs:key>

    <!-- 
        Idegen kulcsok
    -->
    <xs:keyref refer="Csapat_id" name="csapat_stabtag">
      <xs:selector xpath="stabtag"></xs:selector>
      <xs:field xpath="@cs_s"></xs:field>
    </xs:keyref>

    <xs:keyref refer="Csapat_id" name="csapat_jatekos">
      <xs:selector xpath="jatekos"></xs:selector>
      <xs:field xpath="@cs_j"></xs:field>
    </xs:keyref>

    <xs:unique name="edzo_csapat">
        <xs:selector xpath= "edzo"></xs:selector>
        <xs:field xpath="cs_e"></xs:field>
    </xs:unique>

    <xs:keyref refer="Csapat_id" name="csapat_szezon">
      <xs:selector xpath="nevezett_csapat"></xs:selector>
      <xs:field xpath="@ksz_n_id"></xs:field>
    </xs:keyref>

    <xs:keyref refer="Szezon_id" name="szezon_csapat">
      <xs:selector xpath="nevezett_csapat"></xs:selector>
      <xs:field xpath="@sz_a_id"></xs:field>
    </xs:keyref>

  </xs:element>

</xs:schema>

=== HKristof2130/JPTJY2_XMLGyak/Féléves_feladat/DOMParseJPTJY2/ModifiedXMLJPTJY2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--Az nba-ben játszó/dolgozó személyek --><nba xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaJPTJY2.xsd">
    <!--Az nba-ben lejegyzett idények -->
    <szezon sz_id="1">
        <nevezettcsapatok_szama>30</nevezettcsapatok_szama>
        <teljes_szezon>Igen</teljes_szezon>
        <idotartam>
            <kezdet>2021-08-03</kezdet>
            <veg>2022-06-14</veg>
        </idotartam>
    </szezon>
    <szezon sz_id="4">
        <nevezettcsapatok_szama>30</nevezettcsapatok_szama>
        <teljes_szezon>Igen</teljes_szezon>
        <idotartam>
            <kezdet>2019-08-07</kezdet>
            <veg>2020-10-13</veg>
        </idotartam>
    </szezon>
    <szezon sz_id="3">
        <nevezettcsapatok_szama>28</nevezettcsapatok_szama>
        <teljes_szezon>Igen</teljes_szezon>
        <idotartam>
            <kezdet>2010-11-04</kezdet>
            <veg>2011-06-24</veg>
        </idotartam>
        <bajnok>LosAngeles Lakers</bajnok>
    </szezon>
    <!--Az nba-ben lejegyzett csapatok -->
    <csapat cs_id="1">
        <nev>Cleveland Cavaliers</nev>
        <arena>Rocket Morgtage Fieldhouse</arena>
        <bajnoki_cimek>1</bajnoki_cimek>
    </csapat>
    <csapat cs_id="2">
        <nev>Miami Heat</nev>
        <arena>FTX Arena</arena>
        <bajnoki_cimek>3</bajnoki_cimek>
    </csapat>
    <csapat cs_id="3">
        <nev>Dallas Mavericks</nev>
        <arena>American Airlines Center</arena>
        <bajnoki_cimek>1</bajnoki_cimek>
    </csapat>
    <!--Az nba-ben egyes csapatok vezetodezoje -->
    <edzo cs_e="1" e_id="1">
        <nev>J.B Bickerstaff</nev>
        <csapat>Clevleand Cavaliers</csapat>
        <aktiv_szezon>3</aktiv_szezon>
    </edzo>
    <edzo cs_e="3" e_id="2">
        <nev>Jason Kidd</nev>
        <csapat>Dallas Mavericks</csapat>
        <aktiv_szezon>2</aktiv_szezon>
    </edzo>
    <edzo cs_e="2" e_id="3">
        <nev>Erik Spoelstra</nev>
        <csapat>Miami Heat</csapat>
        <aktiv_szezon>15</aktiv_szezon>
    </edzo>
    <!-- Az nba-ben egyes csapatokhoz tartozó stábtag-->
    <stabtag cs_s="2" s_id="1">
        <nev>Chris Quinn</nev>
        <csapat>Miami Heat</csapat>
        <beosztas>Head Coach</beosztas>
    </stabtag>
    <stabtag cs_s="2" s_id="2">
        <nev>Andy Elisburg</nev>
        <csapat>Miami Heat</csapat>
        <beosztas>Head Coach</beosztas>
    </stabtag>
    <stabtag cs_s="1" s_id="3">
        <nev>Luke Walton</nev>
        <csapat>Cleveland Cavaliers</csapat>
        <beosztas>Head Coach</beosztas>
    </stabtag>
    <!-- Az nba-ben az egyes csapatokban játszó játékos-->
    <jatekos cs_j="1" j_id="1">
        <nev>Donovan Mitchell</nev>
        <csapat>Cleveland Cavaliers</csapat>
        <kor>25</kor>
        <pozicio>SG</pozicio>
        <pozicio>PG</pozicio>
    </jatekos>
    <jatekos cs_j="2" j_id="2">
        <nev>Luka Doncic</nev>
        <csapat>Dallas Mavericks</csapat>
        <kor>23</kor>
        <pozicio>PG</pozicio>
        <pozicio>SF</pozicio>
    </jatekos>
    <jatekos cs_j="1" j_id="3">
        <nev>Evan Mobley</nev>
        <csapat>Cleveland Cavaliers</csapat>
        <kor>22</kor>
        <pozicio>PF</pozicio>
        <pozicio>C</pozicio>
    </jatekos>
    <!-- Az nba-be az adott szezonba benevezett csapat-->
    <nevezett_csapat sz_a_id="1" sz_n_id="1">
        <szezon_szama>73</szezon_szama>
        <csapat_neve>Cleveland Cavaliers</csapat_neve>
    </nevezett_csapat>
    <nevezett_csapat sz_a_id="1" sz_n_id="3">
        <szezon_szama>73</szezon_szama>
        <csapat_neve>Dallas Mavericks</csapat_neve>
    </nevezett_csapat>
    <nevezett_csapat sz_a_id="1" sz_n_id="2">
        <szezon_szama>73</szezon_szama>
        <csapat_neve>Miami Heat</csapat_neve>
    </nevezett_csapat>
</nba>

=== HKristof2130/JPTJY2_XMLGyak/Féléves_feladat/DOMParseJPTJY2/XMLJPTJY2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--Az nba-ben játszó/dolgozó személyek -->

<nba xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaJPTJY2.xsd">

    <!--Az nba-ben lejegyzett idények -->

    <szezon sz_id="1">
        <nevezettcsapatok_szama>30</nevezettcsapatok_szama>
        <teljes_szezon>Igen</teljes_szezon>
        <idotartam>
            <kezdet>2021-08-03</kezdet>
            <veg>2022-06-14</veg>
        </idotartam>
    </szezon>

    <szezon sz_id="2">
        <nevezettcsapatok_szama>30</nevezettcsapatok_szama>
        <teljes_szezon>Nem</teljes_szezon>
        <idotartam>
            <kezdet>2019-08-07</kezdet>
            <veg>2020-10-13</veg>
        </idotartam>
    </szezon>

    <szezon sz_id="3">
        <nevezettcsapatok_szama>28</nevezettcsapatok_szama>
        <teljes_szezon>Nem</teljes_szezon>
        <idotartam>
            <kezdet>2010-11-04</kezdet>
            <veg>2011-06-24</veg>
        </idotartam>
    </szezon>

    <!--Az nba-ben lejegyzett csapatok -->

    <csapat cs_id="1">
        <nev>Cleveland Cavaliers</nev>
        <arena>Rocket Morgtage Fieldhouse</arena>
        <bajnoki_cimek>1</bajnoki_cimek>
    </csapat>

    <csapat cs_id="2">
        <nev>Miami Heat</nev>
        <arena>FTX Arena</arena>
        <bajnoki_cimek>3</bajnoki_cimek>
    </csapat>

    <csapat cs_id="3">
        <nev>Dallas Mavericks</nev>
        <arena>American Airlines Center</arena>
        <bajnoki_cimek>1</bajnoki_cimek>
    </csapat>

    <!--Az nba-ben egyes csapatok vezetodezoje -->

    <edzo e_id="1" cs_e="1">
        <nev>J.B Bickerstaff</nev>
        <csapat>Clevleand Cavaliers</csapat>
        <aktiv_szezon>3</aktiv_szezon>
    </edzo>

    <edzo e_id="2" cs_e="3">
        <nev>Jason Kidd</nev>
        <csapat>Dallas Mavericks</csapat>
        <aktiv_szezon>2</aktiv_szezon>
    </edzo>

    <edzo e_id="3" cs_e="2">
        <nev>Erik Spoelstra</nev>
        <csapat>Miami Heat</csapat>
        <aktiv_szezon>15</aktiv_szezon>
    </edzo>

    <!-- Az nba-ben egyes csapatokhoz tartozó stábtag-->

    <stabtag s_id="1" cs_s="2">
        <nev>Chris Quinn</nev>
        <csapat>Miami Heat</csapat>
        <beosztas>Assistant Coach</beosztas>
    </stabtag>

    <stabtag s_id="2" cs_s="2">
        <nev>Andy Elisburg</nev>
        <csapat>Miami Heat</csapat>
        <beosztas>Senior Vice President</beosztas>
    </stabtag>

    <stabtag s_id="3" cs_s="1">
        <nev>Luke Walton</nev>
        <csapat>Cleveland Cavaliers</csapat>
        <beosztas>Assistant Coach</beosztas>
    </stabtag>

    <!-- Az nba-ben az egyes csapatokban játszó játékos-->

    <jatekos j_id="1" cs_j="1">
        <nev>Donovan Mitchell</nev>
        <csapat>Cleveland Cavaliers</csapat>
        <kor>25</kor>
        <pozicio>SG</pozicio>
        <pozicio>PG</pozicio>
    </jatekos>

    <jatekos j_id="2" cs_j="2">
        <nev>Luka Doncic</nev>
        <csapat>Dallas Mavericks</csapat>
        <kor>23</kor>
        <pozicio>PG</pozicio>
        <pozicio>SF</pozicio>
    </jatekos>

    <jatekos j_id="3" cs_j="1">
        <nev>Evan Mobley</nev>
        <csapat>Cleveland Cavaliers</csapat>
        <kor>22</kor>
        <pozicio>PF</pozicio>
        <pozicio>C</pozicio>
    </jatekos>

    <!-- Az nba-be az adott szezonba benevezett csapat-->
    
    <nevezett_csapat sz_a_id="1" sz_n_id="1">
        <szezon_szama>73</szezon_szama>
        <csapat_neve>Cleveland Cavaliers</csapat_neve>
    </nevezett_csapat>

    <nevezett_csapat sz_a_id="1" sz_n_id="3">
        <szezon_szama>73</szezon_szama>
        <csapat_neve>Dallas Mavericks</csapat_neve>
    </nevezett_csapat>

    <nevezett_csapat sz_a_id="1" sz_n_id="2">
        <szezon_szama>73</szezon_szama>
        <csapat_neve>Miami Heat</csapat_neve>
    </nevezett_csapat>
</nba>
